### PR TITLE
fix: gorm-adapter dependency wrong gorm version

### PR DESCRIPTION
**Pull request by closetool**
Signed-off-by: closetool <4closetool3@gmail.com>

Fix: https://github.com/go-admin-team/go-admin/issues/406#issuecomment-830639789

### CODE REVIEW

**Comment by closetool** [comment]
@wenjianzhang @hsluoyz plz review

**Comment by hsluoyz** [comment]
@lwnmengjing

**Review by lwnmengjing — COMMENTED** [review]
原项目不愿意支持sqlite条件编译，这边有定制化开发

**Comment by hsluoyz** [comment]
@lwnmengjing 感谢回复

**Pull request closed without merging**
